import 'dotenv/config';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, Client, EmbedBuilder,
  GatewayIntentBits, PermissionFlagsBits, REST, Routes, SlashCommandBuilder,
  StringSelectMenuBuilder,
} from 'discord.js';

const required = ['DISCORD_TOKEN', 'CLIENT_ID'];
for (const name of required) if (!process.env[name]?.trim()) { console.error(`Missing required environment variable: ${name}`); process.exit(1); }
const snowflake = /^\d+$/;
for (const name of ['CLIENT_ID', 'GUILD_ID']) if (process.env[name]?.trim() && !snowflake.test(process.env[name].trim())) { console.error(`${name} must contain only the numeric Discord ID.`); process.exit(1); }

const dataDir = path.resolve(process.env.DATA_DIR ?? './data');
const configFile = path.join(dataDir, 'guild-config.json');
const storeFile = path.join(dataDir, 'bot-catalog.json');
const ensureJson = async (file) => { await fs.mkdir(dataDir, { recursive: true }); try { return JSON.parse(await fs.readFile(file, 'utf8')); } catch { await fs.writeFile(file, '{}'); return {}; } };
let configs = await ensureJson(configFile);
let catalog = await ensureJson(storeFile);
const save = async (file, value) => { await fs.mkdir(dataDir, { recursive: true }); await fs.writeFile(file, JSON.stringify(value, null, 2)); };
const text = (value, fallback = '') => String(value ?? fallback).trim().slice(0, 1900);
const admin = (command) => command.setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild);
const mod = (command) => command.setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages);
const setup = new SlashCommandBuilder().setName('setup').setDescription('Configure the free bot').addSubcommand((s) => s.setName('welcomer').setDescription('Set welcome and server channels').addChannelOption((o) => o.setName('welcome_channel').setDescription('Welcome channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption((o) => o.setName('bot_commands_channel').setDescription('Bot commands channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption((o) => o.setName('shop_channel').setDescription('Free bot shop channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption((o) => o.setName('verify_channel').setDescription('Verification channel').addChannelTypes(ChannelType.GuildText).setRequired(true))).addSubcommand((s) => s.setName('tickets').setDescription('Set up tickets and inactivity closing').addChannelOption((o) => o.setName('panel_channel').setDescription('Ticket panel channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption((o) => o.setName('logs_channel').setDescription('Ticket log channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption((o) => o.setName('category').setDescription('Ticket category').addChannelTypes(ChannelType.GuildCategory).setRequired(true)).addIntegerOption((o) => o.setName('inactivity_hours').setDescription('Auto-close after inactive hours').setMinValue(1).setMaxValue(24).setRequired(true)));
const commands = [
  setup,
  admin(new SlashCommandBuilder().setName('setuproles').setDescription('Save owner, co-owner, admin, support, and member roles').addRoleOption((o) => o.setName('owner_role').setDescription('Owner role').setRequired(true)).addRoleOption((o) => o.setName('co_owner_role').setDescription('Co-owner role').setRequired(true)).addRoleOption((o) => o.setName('admin_role').setDescription('Admin role').setRequired(true)).addRoleOption((o) => o.setName('support_role').setDescription('Support role').setRequired(false)).addRoleOption((o) => o.setName('member_role').setDescription('Verified member role').setRequired(false))),
  admin(new SlashCommandBuilder().setName('setupserver').setDescription('Create the complete starter server layout')),
  admin(new SlashCommandBuilder().setName('config').setDescription('Show saved bot configuration')),
  new SlashCommandBuilder().setName('stats').setDescription('Show live community bot statistics'),
  new SlashCommandBuilder().setName('rules').setDescription('Post or view the community rules'),
  new SlashCommandBuilder().setName('verify').setDescription('Get the configured member role'),
  new SlashCommandBuilder().setName('help').setDescription('Open the command menu'),
  new SlashCommandBuilder().setName('ping').setDescription('Check bot health'),
  new SlashCommandBuilder().setName('serverinfo').setDescription('Show server information'),
  new SlashCommandBuilder().setName('userinfo').setDescription('Show member information').addUserOption((o) => o.setName('user').setDescription('Member')),
  new SlashCommandBuilder().setName('bots').setDescription('Browse the free bot catalog'),
  new SlashCommandBuilder().setName('shop').setDescription('Open the interactive free bot shop'),
  admin(new SlashCommandBuilder().setName('bot').setDescription('Manage the free bot catalog').addSubcommand((s) => s.setName('add').setDescription('Add a bot').addStringOption((o) => o.setName('name').setDescription('Bot name').setMaxLength(80).setRequired(true)).addStringOption((o) => o.setName('description').setDescription('What it does').setMaxLength(900).setRequired(true)).addStringOption((o) => o.setName('setup').setDescription('Setup instructions').setMaxLength(1500).setRequired(true)).addStringOption((o) => o.setName('link').setDescription('Download or invite link').setMaxLength(500).setRequired(false))).addSubcommand((s) => s.setName('remove').setDescription('Remove a bot').addStringOption((o) => o.setName('name').setDescription('Bot name').setRequired(true))).addSubcommand((s) => s.setName('list').setDescription('List catalog entries'))),
  new SlashCommandBuilder().setName('ticket').setDescription('Open a private support ticket'),
  admin(new SlashCommandBuilder().setName('ticketpanel').setDescription('Post a fresh ticket panel')),
  new SlashCommandBuilder().setName('close').setDescription('Close the current ticket').addStringOption((o) => o.setName('reason').setDescription('Close reason').setMaxLength(300)),
  mod(new SlashCommandBuilder().setName('purge').setDescription('Delete recent messages').addIntegerOption((o) => o.setName('amount').setDescription('1–100 messages').setMinValue(1).setMaxValue(100).setRequired(true))),
  mod(new SlashCommandBuilder().setName('slowmode').setDescription('Set channel slowmode').addIntegerOption((o) => o.setName('seconds').setDescription('0–21600 seconds').setMinValue(0).setMaxValue(21600).setRequired(true))),
  mod(new SlashCommandBuilder().setName('lock').setDescription('Lock the current channel')),
  mod(new SlashCommandBuilder().setName('unlock').setDescription('Unlock the current channel')),
  mod(new SlashCommandBuilder().setName('announce').setDescription('Post an announcement').addStringOption((o) => o.setName('message').setDescription('Announcement').setMaxLength(1900).setRequired(true)).addStringOption((o) => o.setName('title').setDescription('Title').setMaxLength(100))),
  mod(new SlashCommandBuilder().setName('warn').setDescription('Warn a member').addUserOption((o) => o.setName('user').setDescription('Member').setRequired(true)).addStringOption((o) => o.setName('reason').setDescription('Reason').setMaxLength(300))),
  mod(new SlashCommandBuilder().setName('kick').setDescription('Kick a member').addUserOption((o) => o.setName('user').setDescription('Member').setRequired(true)).addStringOption((o) => o.setName('reason').setDescription('Reason'))),
  mod(new SlashCommandBuilder().setName('ban').setDescription('Ban a member').addUserOption((o) => o.setName('user').setDescription('Member').setRequired(true)).addStringOption((o) => o.setName('reason').setDescription('Reason'))),
].map((c) => c.toJSON());

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN);
try { await rest.put(process.env.GUILD_ID ? Routes.applicationGuildCommands(process.env.CLIENT_ID, process.env.GUILD_ID) : Routes.applicationCommands(process.env.CLIENT_ID), { body: commands }); console.log(`Registered ${commands.length} slash commands${process.env.GUILD_ID ? ' for the configured guild' : ' globally'}.`); } catch (error) { console.error('Slash-command registration failed:', error.message); if (error.code === 50001) console.error('Make sure the bot is installed with bot and applications.commands scopes.'); }
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });
const cfg = (id) => configs[id] ??= { welcome: {}, roles: {}, tickets: { activity: {} }, openTickets: {}, warnings: {} };
const mention = (id) => id ? `<#${id}>` : 'not set';
const embed = (color, title, description) => new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).setTimestamp();
const ticketPanel = () => ({ embeds: [embed(0x5865f2, '🎫 Support center', 'Choose a category below or press **Open ticket**. Your ticket is private. Staff can claim it, and inactive tickets close automatically.')], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_open').setLabel('Open ticket').setEmoji('🎫').setStyle(ButtonStyle.Primary)), new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('Choose a ticket category').addOptions({ label: 'Bot setup help', value: 'setup', emoji: '🛠️' }, { label: 'Bug report', value: 'bug', emoji: '🐛' }, { label: 'Bot request', value: 'request', emoji: '🤖' }, { label: 'General support', value: 'general', emoji: '💬' }))] });
const shopMenu = (list) => new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('shop_bot').setPlaceholder('Select a bot to see its details').addOptions(list.slice(0, 25).map((b) => ({ label: b.name.slice(0, 100), value: b.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 100), description: b.description.slice(0, 100), emoji: '🤖' }))));
const ticketControls = () => new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_claim').setLabel('Claim').setEmoji('🙋').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('ticket_close').setLabel('Close').setEmoji('🔒').setStyle(ButtonStyle.Danger));
async function standardLayout(guild) { const names = [['welcome', 'welcome'], ['bot-commands', 'botCommands'], ['bot-shop', 'shop'], ['verify', 'verify'], ['tickets', 'panel'], ['ticket-logs', 'logs']]; const out = {}; for (const [name, key] of names) { let c = guild.channels.cache.find((x) => x.type === ChannelType.GuildText && x.name === name); if (!c) c = await guild.channels.create({ name, type: ChannelType.GuildText, reason: 'Free bot server setup' }); out[key] = c.id; } let category = guild.channels.cache.find((x) => x.type === ChannelType.GuildCategory && x.name === 'Support Tickets'); if (!category) category = await guild.channels.create({ name: 'Support Tickets', type: ChannelType.GuildCategory, reason: 'Free bot ticket setup' }); out.category = category.id; return out; }
async function postPanel(channel) { if (channel?.isTextBased()) await channel.send(ticketPanel()); }
async function openTicket(guild, user, category = 'general') { const server = cfg(guild.id); if (!server.tickets.category) throw new Error('Tickets are not configured. Ask an administrator to run `/setup tickets`.'); const existing = server.openTickets[user.id]; if (existing) return guild.channels.cache.get(existing); const roleId = server.roles.support; const safe = user.username.toLowerCase().replace(/[^a-z0-9-]/g, '').slice(0, 18) || 'user'; const overwrites = [{ id: guild.roles.everyone.id, deny: [PermissionFlagsBits.ViewChannel] }, { id: user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.ReadMessageHistory] }, { id: client.user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.ManageChannels, PermissionFlagsBits.ReadMessageHistory] }]; if (roleId) overwrites.push({ id: roleId, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.ReadMessageHistory] }); const channel = await guild.channels.create({ name: `ticket-${safe}`, type: ChannelType.GuildText, parent: server.tickets.category, permissionOverwrites: overwrites, topic: `category=${category}; opener=${user.id}`, reason: 'Support ticket opened' }); server.openTickets[user.id] = channel.id; server.tickets.activity[channel.id] = Date.now(); server.tickets.categoryByChannel ??= {}; server.tickets.categoryByChannel[channel.id] = category; await save(configFile, configs); await channel.send({ content: `${user}${roleId ? ` <@&${roleId}>` : ''}`, embeds: [embed(0x57f287, `${categoryEmoji(category)} ${categoryLabel(category)} ticket`, 'Explain your issue with screenshots or exact error text if useful. A staff member can claim this ticket. Inactive tickets close automatically.')], components: [ticketControls()], allowedMentions: { users: [user.id], roles: roleId ? [roleId] : [] } }); return channel; }
const categoryEmoji = (v) => ({ setup: '🛠️', bug: '🐛', request: '🤖', general: '💬' }[v] ?? '💬');
const categoryLabel = (v) => ({ setup: 'Bot setup help', bug: 'Bug report', request: 'Bot request', general: 'General support' }[v] ?? 'General support');
async function closeTicket(channel, reason = 'closed') { for (const server of Object.values(configs)) { const owner = Object.entries(server.openTickets ?? {}).find(([, id]) => id === channel.id)?.[0]; if (!owner) continue; delete server.openTickets[owner]; delete server.tickets.activity[channel.id]; delete server.tickets.categoryByChannel?.[channel.id]; await save(configFile, configs); const log = channel.guild.channels.cache.get(server.tickets.logs); if (log?.isTextBased()) await log.send(`🗃️ Closed ${channel.name} — ${reason}.`).catch(() => {}); await channel.delete(`Ticket ${reason}`).catch(() => {}); return true; } return false; }

client.once('clientReady', (bot) => { console.log(`Logged in as ${bot.user.tag} in ${client.guilds.cache.size} server(s).`); if (!client.guilds.cache.size) console.error('The bot is online but not installed in a server.'); });
client.on('guildMemberAdd', async (member) => { const channel = member.guild.channels.cache.get(cfg(member.guild.id).welcome.channel); if (channel?.isTextBased()) await channel.send({ content: `🎉 Welcome ${member} to **${member.guild.name}**! Check <#${cfg(member.guild.id).welcome.verify}> and visit the bot shop.`, allowedMentions: { users: [member.id] } }).catch(() => {}); });
client.on('messageCreate', async (message) => { if (message.author.bot || !message.guild) return; const server = configs[message.guild.id]; if (server?.tickets?.activity?.[message.channel.id]) { server.tickets.activity[message.channel.id] = Date.now(); await save(configFile, configs); } });
setInterval(async () => { const now = Date.now(); for (const server of Object.values(configs)) { const hours = Number(server.tickets?.inactivityHours); if (!hours) continue; for (const [channelId, last] of Object.entries(server.tickets.activity ?? {})) if (now - last >= hours * 3600000) { const channel = client.channels.cache.get(channelId); if (channel) await closeTicket(channel, `${hours} hour(s) inactive`); } } }, 10 * 60 * 1000);

client.on('interactionCreate', async (i) => {
  if (i.isStringSelectMenu() && i.customId === 'shop_bot') { const list = catalog[i.guild.id] ?? []; const key = i.values[0]; const bot = list.find((b) => b.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 100) === key); if (!bot) return i.reply({ content: 'That catalog entry is no longer available.', flags: 64 }); return i.reply({ embeds: [embed(0x5865f2, `🤖 ${bot.name}`, `${bot.description}\n\n**Setup guide**\n${bot.setup}\n\n${bot.link ? `[Download or invite this bot](${bot.link})` : 'Ask staff for the current download or invite link.'}`)] }); }
  if (i.isStringSelectMenu() && i.customId === 'ticket_category') { try { await i.deferReply({ flags: 64 }); const channel = await openTicket(i.guild, i.user, i.values[0]); await i.editReply(`Your ${categoryLabel(i.values[0])} ticket is ready: ${channel}`); } catch (e) { if (i.deferred) await i.editReply(e.message).catch(() => {}); } return; }
  if (i.isButton()) { try { if (i.customId === 'ticket_open') { await i.deferReply({ flags: 64 }); const channel = await openTicket(i.guild, i.user); await i.editReply(`Your ticket is ready: ${channel}`); } else if (i.customId === 'ticket_claim') { await i.deferReply(); await i.editReply(`🙋 This ticket has been claimed by ${i.user}.`); } else if (i.customId === 'ticket_close') { await i.deferReply(); await closeTicket(i.channel, `closed by ${i.user.tag}`); } } catch (e) { console.error('[button]', e.message); if (i.deferred) await i.editReply('This action could not be completed.').catch(() => {}); } return; }
  if (!i.isChatInputCommand()) return;
  try {
    const server = cfg(i.guild?.id ?? 'dm');
    if (i.commandName === 'ping') return i.reply({ embeds: [embed(0x57f287, '🏓 Pong', `API latency: **${client.ws.ping}ms**\nServers: **${client.guilds.cache.size}**\nUptime: <t:${Math.floor((Date.now() - client.readyTimestamp) / 1000) + Math.floor(Date.now() / 1000)}:R>`)] });
    if (i.commandName === 'stats') return i.reply({ embeds: [embed(0x57f287, '📈 Live community stats', `Servers: **${client.guilds.cache.size}**\nMembers served: **${client.guilds.cache.reduce((n, g) => n + (g.memberCount ?? 0), 0)}**\nCatalog bots here: **${(catalog[i.guild.id] ?? []).length}**\nOpen tickets here: **${Object.keys(server.openTickets ?? {}).length}**`)] });
    if (i.commandName === 'rules') return i.reply({ embeds: [embed(0xed4245, '📜 Community rules', '1. Be respectful.\n2. No spam, scams, harassment, or malicious files.\n3. Keep support questions in tickets.\n4. Do not share tokens or private credentials.\n5. Follow Discord Terms of Service.\n6. Staff decisions are final; appeal respectfully.')] });
    if (i.commandName === 'verify') { const roleId = server.roles.member; if (!roleId) return i.reply({ content: 'Verification is not configured. An administrator should run `/setuproles` and select a member role.', flags: 64 }); const member = await i.guild.members.fetch(i.user.id); await member.roles.add(roleId, 'Self-verification'); return i.reply({ content: `✅ You are verified with <@&${roleId}>.`, flags: 64 }); }
    if (i.commandName === 'help') return i.reply({ embeds: [embed(0x5865f2, '✨ Free Bot command center', 'Use `/setupserver` for a complete server, `/bots` for the catalog, and `/ticket` for private support.\n\n**Setup:** `/setup welcomer`, `/setup tickets`, `/setuproles`, `/config`\n**Community:** `/bots`, `/shop`, `/ticket`, `/verify`, `/rules`, `/stats`, `/serverinfo`, `/userinfo`\n**Staff:** `/ticketpanel`, `/close`, `/purge`, `/slowmode`, `/lock`, `/unlock`, `/announce`, `/warn`, `/kick`, `/ban`\n**Catalog:** `/bot add`, `/bot list`, `/bot remove`')], flags: 64 });
    if (i.commandName === 'serverinfo') return i.reply({ embeds: [embed(0x5865f2, `📊 ${i.guild.name}`, `Members: **${i.guild.memberCount}**\nChannels: **${i.guild.channels.cache.size}**\nRoles: **${i.guild.roles.cache.size}**\nOwner: <@${i.guild.ownerId}>`).setThumbnail(i.guild.iconURL({ size: 256 }) ?? '')] });
    if (i.commandName === 'userinfo') { const user = i.options.getUser('user') ?? i.user; const member = await i.guild.members.fetch(user.id).catch(() => null); return i.reply({ embeds: [embed(0x5865f2, `👤 ${user.tag}`, `ID: \`${user.id}\`\nJoined: ${member?.joinedTimestamp ? `<t:${Math.floor(member.joinedTimestamp / 1000)}:R>` : 'unknown'}\nRoles: ${member?.roles.cache.filter((r) => r.id !== i.guild.id).map((r) => r.name).slice(0, 8).join(', ') || 'none'}`).setThumbnail(user.displayAvatarURL({ size: 256 }))] }); }
    if (i.commandName === 'bots' || i.commandName === 'shop') { const list = catalog[i.guild.id] ?? []; if (!list.length) return i.reply({ embeds: [embed(0xfee75c, '🛒 Free bot shop', 'No bots have been added yet. An administrator can add one with `/bot add`.')] }); return i.reply({ embeds: [embed(0x5865f2, '🛒 Free bot shop', 'Choose a bot below to view its description, setup guide, and link.')], components: [shopMenu(list)] }); }
    if (i.commandName === 'setupserver') { const layout = await standardLayout(i.guild); server.welcome = { channel: layout.welcome, botCommands: layout.botCommands, shop: layout.shop, verify: layout.verify }; server.tickets = { ...server.tickets, panel: layout.panel, logs: layout.logs, category: layout.category, inactivityHours: server.tickets.inactivityHours ?? 1, activity: server.tickets.activity ?? {} }; await save(configFile, configs); await postPanel(i.guild.channels.cache.get(layout.panel)); return i.reply({ content: `✅ Complete layout ready. Welcome ${mention(layout.welcome)}, shop ${mention(layout.shop)}, tickets ${mention(layout.panel)}. Ticket timeout: **${server.tickets.inactivityHours} hour(s)**.`, flags: 64 }); }
    if (i.commandName === 'config') return i.reply({ embeds: [embed(0x5865f2, '⚙️ Server configuration', `Welcome: ${mention(server.welcome.channel)}\nCommands: ${mention(server.welcome.botCommands)}\nShop: ${mention(server.welcome.shop)}\nVerify: ${mention(server.welcome.verify)}\nTicket panel: ${mention(server.tickets.panel)}\nLogs: ${mention(server.tickets.logs)}\nCategory: ${mention(server.tickets.category)}\nInactivity: **${server.tickets.inactivityHours ?? 'not set'} hour(s)**\nSupport role: ${server.roles.support ? `<@&${server.roles.support}>` : 'not set'}`)], flags: 64 });
    if (i.commandName === 'setup') { const sub = i.options.getSubcommand(); if (sub === 'welcomer') { server.welcome = { channel: i.options.getChannel('welcome_channel').id, botCommands: i.options.getChannel('bot_commands_channel').id, shop: i.options.getChannel('shop_channel').id, verify: i.options.getChannel('verify_channel').id }; await save(configFile, configs); return i.reply({ content: '✅ Welcome, commands, shop, and verify channels saved.', flags: 64 }); } server.tickets = { ...server.tickets, panel: i.options.getChannel('panel_channel').id, logs: i.options.getChannel('logs_channel').id, category: i.options.getChannel('category').id, inactivityHours: i.options.getInteger('inactivity_hours'), activity: server.tickets.activity ?? {} }; await save(configFile, configs); await postPanel(i.options.getChannel('panel_channel')); return i.reply({ content: `✅ Tickets configured. Tickets close after **${server.tickets.inactivityHours} hour(s)** without a message.`, flags: 64 }); }
    if (i.commandName === 'setuproles') { server.roles = { owner: i.options.getRole('owner_role').id, coOwner: i.options.getRole('co_owner_role').id, admin: i.options.getRole('admin_role').id, support: i.options.getRole('support_role')?.id, member: i.options.getRole('member_role')?.id }; await save(configFile, configs); return i.reply({ content: '✅ Staff roles saved.', flags: 64 }); }
    if (i.commandName === 'ticket') { await i.deferReply({ flags: 64 }); const channel = await openTicket(i.guild, i.user); return i.editReply(`Your ticket is ready: ${channel}`); }
    if (i.commandName === 'ticketpanel') { await postPanel(i.channel); return i.reply({ content: '✅ Ticket panel posted.', flags: 64 }); }
    if (i.commandName === 'close') { await i.deferReply(); const ok = await closeTicket(i.channel, text(i.options.getString('reason'), `closed by ${i.user.tag}`)); return i.editReply(ok ? '🔒 Ticket closed.' : 'This channel is not a tracked ticket.'); }
    if (i.commandName === 'bot') { const sub = i.options.getSubcommand(); const list = catalog[i.guild.id] ?? []; if (sub === 'add') { const name = text(i.options.getString('name')).slice(0, 80); catalog[i.guild.id] = [...list.filter((b) => b.name.toLowerCase() !== name.toLowerCase()), { name, description: text(i.options.getString('description')), setup: text(i.options.getString('setup')), link: i.options.getString('link')?.trim() || '', updatedAt: new Date().toISOString() }]; await save(storeFile, catalog); return i.reply({ content: `✅ **${name}** added to the free bot shop.`, flags: 64 }); } if (sub === 'list') return i.reply({ content: list.length ? list.map((b) => `• **${b.name}** — ${b.description}`).join('\n').slice(0, 1900) : 'The catalog is empty.', flags: 64 }); const name = i.options.getString('name').toLowerCase(); catalog[i.guild.id] = list.filter((b) => b.name.toLowerCase() !== name); await save(storeFile, catalog); return i.reply({ content: '✅ Bot removed if it existed.', flags: 64 }); }
    if (i.commandName === 'purge') { const amount = i.options.getInteger('amount', true); const deleted = await i.channel.bulkDelete(amount, true); return i.reply({ content: `🧹 Deleted ${deleted.size} messages.`, flags: 64 }); }
    if (i.commandName === 'slowmode') { await i.channel.setRateLimitPerUser(i.options.getInteger('seconds', true), `Changed by ${i.user.tag}`); return i.reply({ content: '✅ Slowmode updated.', flags: 64 }); }
    if (i.commandName === 'lock' || i.commandName === 'unlock') { await i.channel.permissionOverwrites.edit(i.guild.roles.everyone, { SendMessages: i.commandName === 'unlock' }); return i.reply({ content: i.commandName === 'lock' ? '🔒 Channel locked.' : '🔓 Channel unlocked.', flags: 64 }); }
    if (i.commandName === 'announce') { const title = text(i.options.getString('title'), '📢 Announcement'); return i.reply({ embeds: [embed(0xed4245, title, text(i.options.getString('message')))], allowedMentions: { parse: [] } }); }
    if (['warn', 'kick', 'ban'].includes(i.commandName)) { const user = i.options.getUser('user', true); const member = await i.guild.members.fetch(user.id).catch(() => null); const reason = text(i.options.getString('reason'), `Action by ${i.user.tag}`); if (!member) return i.reply({ content: 'Member not found.', flags: 64 }); if (i.commandName === 'warn') { server.warnings[user.id] = [...(server.warnings[user.id] ?? []), { reason, by: i.user.id, at: new Date().toISOString() }]; await save(configFile, configs); return i.reply(`⚠️ ${user} was warned. Reason: ${reason}`); } if (i.commandName === 'kick') await member.kick(reason); else await member.ban({ reason }); return i.reply(`✅ ${user.tag} was ${i.commandName}ed. Reason: ${reason}`); }
  } catch (error) { console.error(`[${i.commandName}]`, error.message); const reply = { content: 'That action failed. Check bot permissions, role hierarchy, and channel settings.', flags: 64 }; if (i.replied || i.deferred) await i.followUp(reply).catch(() => {}); else await i.reply(reply).catch(() => {}); }
});
client.login(process.env.DISCORD_TOKEN).catch((error) => { console.error('Could not log in:', error.message); process.exit(1); });
process.on('SIGINT', () => { client.destroy(); process.exit(0); });
process.on('SIGTERM', () => { client.destroy(); process.exit(0); });
